---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker

inputs:
- name: docker-image
- name: project-src

run:
  path: sh
  args:
  - project-src/concourse/tasks/run_container_image_tests.sh
